name: Build and test

on: [push, pull_request]

jobs:
  package:
    name: Maven Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode -show-version --update-snapshots --errors package
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@afe6793191b75b608954023a46831a3fe10048d4 # v1.7.0
        if: always() # also run if build step failed
        with:
          name: JUnit Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
